[package]
name = "dell_log_fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
dhcproto = "0.12"
tokio = { version = "1", features = ["full"] }
rpassword = "7.3"
colored = "2.1"
indicatif = "0.17"
chrono = "0.4"
if-addrs = "0.13"